name: Create pre-release
"on":
  pull_request:
    types:
      - opened

jobs:
  build:
    if: ${{ github.actor != 'dependabot'}}
    runs-on: ubuntu-latest
    outputs:
      release: ${{ steps.rcrelease.outputs.release }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 12.x
      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: npm-${{ env.cache-name }}-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-${{ env.cache-name }}-${{ matrix.node-version }}-
            npm-${{ env.cache-name }}-
            npm-
      - run: npm install
      - name: Tag a rc release
        id: rcrelease
        uses: actionsdesk/semver@0.6.0-rc.8
        with:
          bump: patch
          prerelease: withBuildNumber
          prelabel: rc


